apiVersion: v1
kind: ConfigMap
metadata:
  name: base
data:
  key: configmap
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: override
data:
  key: configmap-override
---

apiVersion: v1
kind: Secret
metadata:
  name: base
type: Opaque
stringData:
  key: secret
---

apiVersion: v1
kind: Secret
metadata:
  name: override
type: Opaque
stringData:
  key: secret-override
