apiVersion: batch/v1
kind: Job
metadata:
  name: job-06
spec:
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: env-test
        image: busybox
        command:
        - /bin/sh
        - -c
        args:
        - export key=command && env
        env:
        - name: key
          value: inline
        envFrom:
        - configMapRef:
            name: base
        - configMapRef:
            name: override
        - secretRef:
            name: base
        - secretRef:
            name: override
