apiVersion: batch/v1
kind: Job
metadata:
  name: job-04
spec:
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: env-test
        image: busybox
        command:
        - env
        envFrom:
        - configMapRef:
            name: base
        - configMapRef:
            name: override
        - secretRef:
            name: base
        - secretRef:
            name: override
